Add canadian building support on Linux ARM64

diff --git a/scripts/make_canadian b/scripts/make_canadian
--- a/scripts/make_canadian
+++ b/scripts/make_canadian
@@ -1,15 +1,11 @@
 #!/usr/bin/env bash
 
-# This script only runs on Linux x64.
+# This script only runs on Linux x64 or ARM64
+# (only Linux x64 for *-gnu hosts).
 
 set -e -o pipefail
 
-GH_URL_GNU="https://github.com/cross-tools"
-GH_URL_MUSL="https://github.com/Matrix3600"
-GH_URL_MINGW="https://github.com/Matrix3600"
-GH_VER_GNU=20260515
-GH_VER_MUSL=20260616
-GH_VER_MINGW=20260616
+. "$(dirname "$0")/tools/common.sh"
 
 
 #
@@ -101,63 +97,48 @@ function get_host_toolchain()
 {
 	local HOST="$1"
 
-	local host_toolchain_tarname="linux-x64_${HOST}.tar.xz"
+	local build
+	build="$(get_build_machine_type)"
+	case $build in
+		linux-x64) ;;
+		linux-arm64)
+			case $HOST in
+				*-gnu)
+					echo "[ERROR] Only Linux x64 build machine is supported for host ${HOST}." >&2
+					return 1
+					;;
+			esac
+			;;
+		*)
+			echo "[ERROR] Build machine not supported (${build})." >&2
+			return 1
+			;;
+	esac
+	local arch="${build##*-}"
+	local host_toolchain_tarname="${build}_${HOST}.tar.xz"
 	local name="$host_toolchain_tarname"
 	if [ ! -f "$host_toolchain_tarname" ]; then
 		local url=""
-		case ${HOST} in
+		case $HOST in
 			*-gnu)
 				name="${HOST}.tar.xz"
-				url="${GH_URL_GNU}/gnu-cross/releases/download/${GH_VER_GNU}/${name}"
+				url="${CROSS_GNU_URL}/gnu-cross/releases/download/${CROSS_GNU_VER}/${name}"
 				;;
 			*-musl)
-				url="${GH_URL_MUSL}/musl-cross/releases/download/x64-${GH_VER_MUSL}/${name}"
+				url="${CROSS_MUSL_URL}/musl-cross/releases/download/${arch}-${CROSS_MUSL_VER}/${name}"
 				;;
 			*-mingw32)
-				url="${GH_URL_MINGW}/mingw-cross/releases/download/x64-${GH_VER_MINGW}/${name}"
+				url="${CROSS_MINGW_URL}/mingw-cross/releases/download/${arch}-${CROSS_MINGW_VER}/${name}"
 				;;
 		esac
 		if ! wget -nv -nc -T 120 --tries=20 "$url"; then
-			echo "[ERROR] Host not supported (${HOST})."
+			echo "[ERROR] Host not supported (${HOST})." >&2
 			return 1
 		fi
 		if [ "$name" != "$host_toolchain_tarname" ]; then
 			mv "$name" "$host_toolchain_tarname"
 		fi
 	fi
-}
-
-
-function build_crosstool_ng()
-{
-	sudo rm -rf crosstool-ng
-	mkdir crosstool-ng
-	local install_dir="$(pwd)/crosstool-ng"
-
-	pushd builder
-
-	# Patch
-	git clean -fdx
-	git reset --hard HEAD
-	if [ -d "../patches" ]; then
-		find "../patches" -type f -name "*.patch" -print0 | sort -z | \
-			while IFS= read -r -d '' file; do
-				echo "*** ${file#../patches/}"
-				patch -Np1 -i "$file"
-			done
-	fi
-
-	./bootstrap
-	./configure --prefix="${install_dir}"
-	make -j$(nproc)
-	make install
-	popd
-	sudo chown -R root:0 crosstool-ng
-
-	local name="crosstool-ng.tar.xz"
-	echo -e "\nCreating \"${name}\" ...\n"
-	tar -cJvf "$name" crosstool-ng
-	sudo rm -rf crosstool-ng
 }
 
 
@@ -175,7 +156,7 @@ function build_target()
 		cd -- "$src_dir" &>/dev/null && pwd)"
 	set -e
 	if [ -z "$source_dir" ]; then
-		echo "[ERROR] Source directory invalid (${src_dir})."
+		echo "[ERROR] Source directory invalid (${src_dir})." >&2
 		return 1
 	fi
 
@@ -210,12 +191,16 @@ function build_target()
 	echo -e "\n******\n"
 
 	# Install the host toolchain
-	tar -xf "../linux-x64_${HOST}.tar.xz"
+	local build
+	build="$(get_build_machine_type)"
+	tar -xf "../${build}_${HOST}.tar.xz"
 
 	(
 		export PATH="$(pwd)/${HOST}/bin:$PATH"
 		../crosstool-ng/bin/ct-ng build
 	)
+
+	show_progress_message "Finalizing toolchain"
 
 	# Dynamic library for host
 	find "musl-cross" -maxdepth 2 -exec chmod +w {} \;
@@ -244,22 +229,13 @@ function build_target()
 	local linkname="musl-cross/${TARGET}/sysroot/lib/ld-musl-powerpc.so.1"
 	if [[ $TARGET == "powerpcle-unknown-linux-musl" && \
 		$(readlink "$linkname") == "/usr/lib/libc.so" ]]; then
-		pushd "$(dirname "$linkname")"
 		echo "Fixing invalid absolute link ${linkname}"
-		sudo ln -rsf "../usr/lib/libc.so" "$(basename "$linkname")"
-		popd
+		sudo ln -sf "../usr/lib/libc.so" "$linkname"
 	fi
 
-	local host_name="$(sed 's/-unknown//g' <<< "$HOST")"
-	case $host_name in
-		aarch64-linux-gnu)
-			host_name="linux-arm64" ;;
-		x86_64-linux-gnu)
-			host_name="linux-x64" ;;
-		x86_64-w64-mingw32)
-			host_name="win-x64" ;;
-	esac
-	if [[ $host_name =~ win-* ]]; then
+	local host_type
+	host_type="$(get_host_type "$HOST")"
+	if [[ $host_type =~ win-* ]]; then
 		rename_files_windows "musl-cross/${TARGET}"
 	fi
 
@@ -268,16 +244,21 @@ function build_target()
 	mv musl-cross ${TARGET}
 	sudo chown -R root:0 ${TARGET}
 
-	if [[ $host_name =~ win-* ]]; then
-		local name="${host_name}_${TARGET}.7z"
-		echo -e "\nCreating \"${name}\" ...\n"
+	if [[ $host_type =~ win-* ]]; then
+		local name="${host_type}_${TARGET}.7z"
+
+		show_progress_message "Creating \"${name}\""
+
 		7z a -mx9 "../${name}" "${TARGET}"
 	else
-		local name="${host_name}_${TARGET}.tar.xz"
-		echo -e "\nCreating \"${name}\" ...\n"
+		local name="${host_type}_${TARGET}.tar.xz"
+
+		show_progress_message "Creating \"${name}\""
+
 		tar -cJvf "../${name}" "${TARGET}"
 	fi
-	local hash="$(sha256sum "../${name}" | awk '{ print $1 }')"
+	local hash
+	hash="$(sha256sum "../${name}" | awk '{ print $1 }')"
 	printf '%s *%s\n' "$hash" "$name" > "../${name}.sha256"
 	popd
 	sudo rm -rf build
@@ -297,22 +278,22 @@ else
 fi
 
 if [[ -z $HOST && $TARGET != "crosstool-ng" ]]; then
-	echo "[ERROR] Host is missing."
+	echo "[ERROR] Host is missing." >&2
 	exit 1
 fi
 
 if [ -z "$TARGET" ]; then
-	echo "[ERROR] Target is missing."
+	echo "[ERROR] Target is missing." >&2
 	exit 1
 fi
 
 if [[ $TARGET != "crosstool-ng" && ! -f "targets/${TARGET}/config" ]]; then
-	echo "[ERROR] Target not supported (${TARGET})."
+	echo "[ERROR] Target not supported (${TARGET})." >&2
 	exit 1
 fi
 
 if [ "$HOST" == "$TARGET" ]; then
-	echo "[ERROR] Target and host are identical."
+	echo "[ERROR] Target and host are identical." >&2
 	exit 1
 fi
 
