Update pre-download

diff --git a/scripts/pre-download b/scripts/pre-download
--- a/scripts/pre-download
+++ b/scripts/pre-download
@@ -72,7 +72,7 @@ trim() {
 
 destdir=$1
 if [ -z "$destdir" ]; then
-	destdir="~/src"
+	destdir="source-tarballs"
 fi
 
 mkdir -p "$destdir"
@@ -84,6 +84,11 @@ fi
 config_file="pre-download-config"
 script_dir=$(cd -- "$(dirname -- "$0")" &>/dev/null && pwd)
 
+if [ ! -f "$script_dir/$config_file" ]; then
+	echo "[ERROR] Configuration file not found ($script_dir/$config_file)"
+	exit 2
+fi
+
 while IFS= read -r line <&3
 do
 	line=${line%%#*}	# Remove comments
@@ -94,7 +99,7 @@ do
 		re="^(https?://.+/)(.+)-([^-]*)(\.tar\..+)$"
 		if [[ ! $url =~ $re ]]; then
 			echo "[ERROR] Invalid package URL (${url})"
-			exit 2
+			exit 3
 		fi
 		path=${BASH_REMATCH[1]}
 		package=${BASH_REMATCH[2]}
